fun main() {
    print("student Enrollment No.:")
    val enrollmentNo = readln().toLong()
    print("student Name:")
    val name = readln()
    print("student Branch:")
    val branch = readln()
    print("student Class:")
    val studentClass = readln()
    print("student Batch:")
    val batch = readln()
    print("student College Name:")
    val collegeName = readln()
    print("student University Name:")
    val universityName = readln()
    print("student Age:")
    val age = readln().toInt()

    println("********************")
    println("Student's Data:")
    println("Enrollment No.:$enrollmentNo")
    println("Name:$name")
    println("Age:$age")
    println("Branch:$branch")
    println("Class:$studentClass")
    println("Batch:$batch")
    println("College Name:$collegeName")
    println("University Name:$universityName")
}